name: covid19
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.1
  - plotly=4.5.2
  - python=3.7.6
  - statsmodels=0.11.0
  - pycountry=19.8.18
  - pypdf2
  - pre_commit=2.2.0
